version: '3.8'

services:
  invigo-server:
    build: .
    image: jarebear/invigo-server:latest
    container_name: invigo-server
    restart: unless-stopped
    ports:
      - "5057:5057"
    environment:
      PYTHONPATH: "/app"
      PORT: "5057"
      DATA_PATH: "/web/Invigo-server"