def convert(data: dict) -> dict:
    return {
        "name": data["name"],
        "categories": data.get("categories", []),
        "category_quantities": data.get("category_quantities", {}),
        "inventory_data": {
            "quantity": data.get("quantity", 0),
            "red_quantity_limit": data.get("red_quantity_limit", 10),
            "yellow_quantity_limit": data.get("yellow_quantity_limit", 20),
        },
        "meta_data": {
            "machine_time": data.get("machine_time", 0.0),
            "weight": data.get("weight", 0.0),
            "part_number": data.get("part_number", ""),
            "image_index": data.get("image_index", ""),
            "surface_area": data.get("surface_area", 0.0),
            "cutting_length": data.get("cutting_length", 0.0),
            "file_name": data.get("file_name", ""),
            "piercing_time": data.get("piercing_time", 0.0),
            "piercing_points": data.get("piercing_points", 0),
            "gauge": data.get("gauge", ""),
            "material": data.get("material", ""),
            "shelf_number": data.get("shelf_number", ""),
            "sheet_dim": data.get("sheet_dim", ""),
            "part_dim": data.get("part_dim", ""),
            "geofile_name": data.get("geofile_name", ""),
            "modified_date": data.get("modified_date", ""),
            "bend_hits": len(data.get("bending_files", [])),
            "notes": data.get("notes", ""),
            "quantity_on_sheet": data.get("quantity_on_sheet", 0),
        },
        "prices": {
            "price": data.get("price", 0.0),
            "cost_of_goods": data.get("cost_of_goods", 0.0),
            "bend_cost": data.get("bend_cost", 0.0),
            "labor_cost": data.get("labor_cost", 0.0),
            "cost_for_paint": data.get("cost_for_paint", 0.0),
            "cost_for_primer": data.get("cost_for_primer", 0.0),
            "cost_for_powder_coating": data.get("cost_for_powder_coating", 0.0),
            "matched_to_sheet_cost_price": 0.0,
        },
        "paint_data": {
            "uses_paint": data.get("uses_paint", False),
            "paint_name": data.get("paint_name") or "",
            "paint_item": None,
            "paint_overspray": data.get("paint_overspray", 66.67),
        },
        "primer_data": {
            "uses_primer": data.get("uses_primer", False),
            "primer_name": data.get("primer_name") or "",
            "primer_item": None,
            "primer_overspray": data.get("primer_overspray", 66.67),
        },
        "powder_data": {
            "uses_powder": data.get("uses_powder_coating", False),
            "powder_name": data.get("powder_name") or "",
            "powder_item": None,
            "powder_transfer_efficiency": data.get("powder_transfer_efficiency", 66.67),
        },
        "workspace_data": {
            "bending_files": data.get("bending_files", []),
            "welding_files": data.get("welding_files", []),
            "cnc_milling_files": data.get("cnc_milling_files", []),
            "flowtag": data.get("flow_tag", {}),
            "flow_tag_data": data.get("flow_tag_data", {}),
        },
    }
