import { FlowtagData } from "./flowtag";

export interface LaserCutPartData {
    id: number;
    name: string;
    part_number: string;
    gauge: string;
    material: string;
    part_dim: string;
    machine_time: number;
    weight: number;
    surface_area: number;
    cutting_length: number;
    piercing_time: number;
    piercing_points: number;
    shelf_number: string;
    sheet_dim: string;
    file_name: string;
    geofile_name: string;
    modified_date: string;
    notes: string;
    image_index: string;
    price: number;
    cost_of_goods: number;
    bend_cost: number;
    labor_cost: number;
    recut: boolean;
    recut_count: number;
    recut_count_notes: number;
    uses_primer: boolean;
    primer_name: string | null;
    primer_overspray: number;
    cost_for_primer: number;
    uses_paint: boolean;
    paint_name: string | null;
    paint_overspray: number;
    cost_for_paint: number;
    uses_powder_coating: boolean;
    powder_name: string | null;
    powder_transfer_efficiency: number;
    cost_for_powder_coating: number;
    recoat: boolean;
    recoat_count: number;
    bending_files: string[];
    welding_files: string[];
    cnc_milling_files: string[];
    categories: string[];
    category_quantities: Record<string, number>;
    quantity: number;
    quantity_on_sheet: number;
    red_quantity_limit: number;
    yellow_quantity_limit: number;
    flow_tag: FlowtagData;
    current_flow_tag_index: number;
    current_flow_tag_status_index: number;
    timer: Record<string, unknown>;
    flow_tag_data: Record<string, { expected_time_to_complete: number }>;
}
